import { customerProject, assess, coverage, decisionFreshness, today } from './core.js';
export const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
const esc = escapeHtml;
const paragraph = (value) => `<p>${esc(value).replace(/\n/g, '<br>')}</p>`;
const label = (key, value) => `<div><dt>${esc(key)}</dt><dd>${esc(value || 'Not provided')}</dd></div>`;
export async function renderHandover(project, store) {
  const safe = customerProject(project); const health = await store.health(safe); const readiness = assess(safe, health);
  const states = new Map(coverage(safe, health).criteria.map((c) => [c.id, c]));
  const now = today();
  const names = new Map(safe.criteria.map((c) => [c.id, c.name]));
  const linked = (record) => record.criterionIds.length ? `<p class="links">Linked criteria: ${record.criterionIds.map((key) => esc(names.get(key))).join(' · ')}</p>` : '<p class="links">No customer-visible criterion links.</p>';
  const content = [];
  for (const e of safe.evidence) {
    const attachments = [];
    for (const a of safe.attachments.filter((a) => a.evidenceId === e.id)) {
      let link = `<strong>${esc(a.name)}</strong> — ${esc(health[a.id])}`;
      if (health[a.id] === 'ok') {
        const bytes = await store.readAttachment(a);
        link = `<a href="data:application/octet-stream;base64,${bytes.toString('base64')}" download="${esc(a.name)}">Download ${esc(a.name)}</a> — ${a.size.toLocaleString('en-US')} bytes · verified`;
      }
      attachments.push(`<li>${link}<code>SHA-256 ${esc(a.sha256)}</code></li>`);
    }
    const freshness = e.collectedAt > now ? 'Future-dated — review required' : (Date.parse(now) - Date.parse(e.collectedAt)) / 86400000 > e.staleAfterDays ? 'Stale — refresh required' : 'Within freshness window';
    content.push(`<article><h3>${esc(e.name)}</h3>${paragraph(e.summary)}<dl>${label('Source', e.source)}${label('Owner', e.owner)}${label('Collected', e.collectedAt)}${label('Freshness window', `${e.staleAfterDays} days`)}${label('Evidence freshness', freshness)}</dl>${linked(e)}${attachments.length ? `<ul class="files">${attachments.join('')}</ul>` : '<p class="muted">No customer-visible attachments.</p>'}</article>`);
  }
  const section = (number, title, body) => `<section><h2><span>${number}</span>${title}</h2>${body || '<p class="muted">No customer-visible records in this section.</p>'}</section>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"><title>${esc(safe.charter.title || 'Pilot handover')} · Proofpack</title><style>
  :root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#f5f3ed;color:#243b32;font:15px/1.65 system-ui,sans-serif}main{max-width:1000px;margin:0 auto;padding:56px 52px 80px}.brand{font-weight:750;font-size:18px;letter-spacing:-.5px}.eyebrow{font:700 11px system-ui;letter-spacing:2px;text-transform:uppercase;color:#6e7468;margin-top:48px}h1{font:500 clamp(32px,5vw,58px)/1.12 Georgia,serif;letter-spacing:-1.5px;margin:20px 0}h2{font:500 28px Georgia,serif;margin:0 0 22px}h2 span{font:12px system-ui;color:#9b7a36;margin-right:18px}h3{font-size:17px;margin:0 0 8px}p{white-space:normal;overflow-wrap:anywhere}section{border-top:1px solid #d6d9cc;margin-top:38px;padding-top:30px}article{background:#fffdf8;padding:22px 24px;margin:16px 0;border:1px solid #dce0d4;border-radius:6px;break-inside:avoid}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px 26px}dt{font-size:10px;letter-spacing:1px;text-transform:uppercase;color:#747a6c}dd{margin:3px 0;white-space:pre-wrap;overflow-wrap:anywhere}.status{display:inline-block;padding:3px 10px;font-size:11px;text-transform:uppercase;letter-spacing:.6px;background:#e7eddf;border-radius:4px;margin-bottom:10px}.blocked,.unmet{background:#f6e7cb;color:#795316}.unassessed{background:#ebece7;color:#63685e}.notice{background:#ece7d9;border-left:3px solid #b88636;padding:15px 20px}.muted,.links{color:#74796e;font-size:13px}code{display:block;overflow-wrap:anywhere;font-size:10px;color:#697063;margin-top:5px}.files{padding-left:18px}.files li{margin-top:12px}a{color:#205644}footer{border-top:1px solid #d6d9cc;padding-top:18px;margin-top:44px;font-size:11px;color:#74796e}ul{padding-left:20px}.warn{color:#76551e} .muted,.links,.eyebrow,dt,footer,code{color:#52624e}h2 span{color:#755b2b} @media(max-width:650px){main{padding:28px 20px}dl{grid-template-columns:1fr}article{padding:18px}}@media print{body{background:white;color:#172d23}main{max-width:none;padding:0}article{background:white}h1{font-size:38px}.print-note{display:none}a{color:inherit;text-decoration:none}section{break-inside:auto}h2,h3{break-after:avoid}@page{size:A4;margin:18mm}}
  </style></head><body><main><div class="brand">Proofpack <span class="muted">/ Customer handover</span></div>${safe.charter.demo ? '<p class="notice"><strong>FICTIONAL DEMONSTRATION</strong> — All organizations, people, results, and attachments are synthetic examples. Not real customer evidence.</p>' : ''}<p class="eyebrow">Pilot evidence & operational handover</p><h1>${esc(safe.charter.title || 'Untitled pilot')}</h1><p>${esc(safe.charter.customer || 'Customer not specified')}</p>${paragraph(safe.charter.objective)}<dl>${label('Owners', safe.charter.owners)}${label('Pilot dates', `${safe.charter.startDate || 'Not set'} — ${safe.charter.endDate || 'Not set'}`)}</dl><p class="notice"><strong>${readiness.ready ? 'Customer-view checks clear' : 'Review required'} · ${readiness.met}/${readiness.total} current criterion passes; ${readiness.historicalMet}/${readiness.total} historical met assessments.</strong><br>Customer-visible records and attachments only. These checks do not include internal records and are not a whole-workspace sign-off. Evidence never implies success; each criterion requires an explicit review. Changed or legacy-unverified reviews and stale or unverified evidence do not establish a current pass. Historical outcomes are preserved, not silently rewritten.</p><p class="print-note muted">This document is self-contained and works offline. Use your browser’s Print → Save as PDF. Attachments are embedded as downloads in HTML; PDF printing does not embed attachment bytes. Links and filenames are not opened automatically.</p>
  ${section('01', 'Success criteria', safe.criteria.map((c) => {
    const state = states.get(c.id);
    const previous = (c.reviews || []).slice(0, -1);
    return `<article><span class="status ${state.currentMet ? 'met' : 'unassessed'}">${state.currentMet ? 'Current pass' : 'Current pass not established'}</span><h3>${esc(c.name)}</h3><dl>${label('Historical assessment', c.status)}${label('Review freshness', state.freshness)}${label('Metric', c.metric)}${label('Baseline', c.baseline)}${label('Target threshold', c.threshold)}${label('Target date', c.targetDate)}${label('Owner', c.owner)}${label('Reviewer', c.reviewer || 'Awaiting explicit review')}${label('Review date', c.reviewedAt)}</dl>${paragraph(c.rationale || 'Not assessed. Linked evidence is not a success decision.')}${previous.length ? `<details><summary>Earlier historical reviews — not current passes</summary>${previous.map((r) => `<dl>${label('Assessment', r.status)}${label('Reviewer', r.reviewer)}${label('Review date', r.date)}</dl>${paragraph(r.rationale)}`).join('')}</details>` : ''}</article>`;
  }).join(''))}
  ${section('02', 'Evidence register', content.join(''))}
  ${section('03', 'Risks & mitigations', safe.risks.map((r) => `<article><span class="status">${esc(r.severity)} · ${esc(r.status)}</span><h3>${esc(r.name)}</h3>${paragraph(r.detail)}<dl>${label('Owner', r.owner)}${label('Mitigation', r.mitigation)}</dl>${linked(r)}</article>`).join(''))}
  ${section('04', 'Pilot decisions & decision log', `${(safe.decisionReviews || []).map((d, index, reviews) => {
    const freshness = decisionFreshness(safe, d);
    return `<article><span class="status ${freshness === 'changed' ? 'blocked' : ''}">${esc(d.outcome)} · ${esc(freshness)}</span><h3>${index === reviews.length - 1 ? 'Latest shared pilot decision' : 'Earlier shared pilot decision (historical)'}</h3>${freshness === 'changed' ? '<p class="notice">Reviewed material has changed. This historical decision is not current approval; explicit re-review is required.</p>' : '<p class="muted">Current customer-view snapshot only; not a whole-workspace sign-off.</p>'}${paragraph(d.rationale)}<dl>${label('Reviewer', d.reviewer)}${label('Review date', d.date)}${label('Conditions', d.conditions || 'No conditions recorded')}</dl></article>`;
  }).join('') || '<p class="notice">No customer-visible proceed, hold or stop review has been recorded. A decision log entry is not pilot approval.</p>'}${safe.decisions.map((d) => `<article><h3>${esc(d.name)}</h3>${paragraph(d.detail)}<dl>${label('Owner', d.owner)}${label('Date', d.date)}</dl>${linked(d)}</article>`).join('')}`)}
  ${section('05', 'Operational handover', safe.checklist.map((c) => `<article><span class="status">${c.done ? 'Complete' : 'Open'}</span><h3>${esc(c.name)}</h3>${paragraph(c.detail)}<dl>${label('Owner', c.owner)}${label('Due date', c.dueDate)}</dl></article>`).join(''))}
  ${section('06', 'Customer-view review notes', readiness.warnings.length ? `<ul class="warn">${readiness.warnings.map((w) => `<li>${esc(w.message)}</li>`).join('')}</ul>` : '<p>No automated customer-view warnings. Human approval is still required.</p>')}
  <footer>Prepared locally with Proofpack · ${esc(new Date().toISOString())} · Customer-visible export · Record visibility is not semantic redaction: review every shared free-text field before distributing.</footer></main></body></html>`;
}
