import { z, id, page, paginate, operation as op, makeProduct } from './runtime.mjs';
import { ProofpackService } from '../service.mjs';
import { validateBackup, criterionFingerprint, pilotFingerprint } from '../core.js';
import { fault, workspaceFile, fingerprint, restorePreview } from './workspace.mjs';
import { open, constants } from 'node:fs/promises';
import { edit, records } from './schemas.mjs';
const object = z.record(z.string(), z.unknown());
const service = async c => new ProofpackService(c.root).open();
const target = { pilotId: z.string().uuid() };
const change = { ...target, revision: z.number().int().nonnegative() };
const operations = {
  'pilot.list': op('List pilot identities and library revision. Archives are retained.', page, async (i, c) => { const library = (await service(c)).library.snapshot(); return { ...paginate(library.pilots, i), revision: library.revision, defaultPilotId: library.defaultPilotId }; }),
  'pilot.create': op('Create an isolated pilot at the expected library revision.', { title: z.string().trim().min(1).max(200), revision: z.number().int().nonnegative() }, async (i, c) => (await service(c)).library.create(i), { write: true }),
  'pilot.archive': op('Reversibly archive or unarchive a pilot at the expected library revision.', { ...change, archived: z.boolean() }, async (i, c) => (await service(c)).library.archive(i.pilotId, { revision: i.revision, archived: i.archived }), { write: true }),
  'pilot.get': op('Read a complete private pilot snapshot and current revision.', target, async (i, c) => ({ project: (await service(c)).snapshot(i.pilotId) })),
  'pilot.check': op('Check criterion coverage, evidence freshness, attachments and outstanding handover actions.', target, async (i, c) => { const { project, ...checks } = await (await service(c)).status(i.pilotId); return { revision: project.revision, ...checks }; }),
  'record.edit': op('Add, update or remove a criterion, evidence item, risk, decision note or task; update charter fields. Evidence never creates a review.', { ...change, section: z.enum(['charter', 'criteria', 'evidence', 'risks', 'decisions', 'checklist']), action: z.enum(['add', 'update', 'remove']), recordId: id.optional(), record: z.union(Object.values(records).map(schema => schema.partial())).default({}), dryRun: z.boolean().default(false) }, async (i, c) => (await service(c)).record(i), { write: true }),
  'record.list': op('Read a bounded page of records from one pilot section.', { ...target, section: z.enum(['criteria', 'evidence', 'risks', 'decisions', 'checklist', 'attachments']), ...page }, async (i, c) => { const p = (await service(c)).snapshot(i.pilotId); return { ...paginate(p[i.section], i), revision: p.revision }; }),
  'record.schema': op('Discover allowed record fields and required properties before adding or editing a record.', { section: z.enum(['charter', 'criteria', 'evidence', 'risks', 'decisions', 'checklist']) }, async i => ({ section: i.section, schema: z.toJSONSchema(records[i.section]), defaults: { visibility: 'internal', criterionIds: [] }, notice: 'Omit assessment fields; reviews are separate operations. record.edit accepts partial fields on update.' })),
  'attachment.get': op('Download a verified pilot attachment by ID. May contain internal evidence.', { ...target, attachmentId: id, includePrivate: z.literal(true) }, async (i, c) => { const s = await service(c), store = s.store(i.pilotId); const meta = store.project.attachments.find(a => a.id === i.attachmentId); if (!meta) throw fault('NOT_FOUND', 'Attachment not found.', 404); const bytes = await store.readAttachment(meta); return { artifact: { filename: meta.name, mediaType: meta.type, bytes: bytes.length, sha256: meta.sha256, base64: bytes.toString('base64') } }; }),
  'attachment.add': op('Attach a regular workspace-relative file to existing evidence; verify bytes and SHA-256. Defaults to internal.', { ...change, evidenceId: id, file: z.string().min(1).max(240), name: z.string().min(1).max(160), type: z.string().max(120).default('application/octet-stream'), visibility: z.enum(['internal', 'customer']).default('internal') }, async (i, c) => { const file = await workspaceFile(c.root, i.file); const handle = await open(file, constants.O_RDONLY | constants.O_NOFOLLOW); let bytes; try { const st = await handle.stat(); if (!st.isFile() || st.size < 1 || st.size > 8 * 1024 * 1024) throw fault('INVALID_FILE', 'Attachment must be a regular file of 1 byte to 8 MiB.'); bytes = await handle.readFile(); } finally { await handle.close(); } return { project: await (await service(c)).upload(i.pilotId, { revision: i.revision, evidenceId: i.evidenceId, name: i.name, type: i.type, visibility: i.visibility, data: bytes.toString('base64') }) }; }, { write: true }),
  'review.propose': op('Record an internal agent proposal tied to the reviewed inputs. Does not satisfy approval or success gates.', { ...change, criterionId: id.optional(), outcome: z.enum(['met', 'unmet', 'blocked', 'proceed', 'hold', 'stop']), rationale: z.string().trim().min(1).max(4000), actor: z.string().trim().min(1).max(200), conditions: z.string().max(4000).default(''), dryRun: z.boolean().default(false) }, async (i, c) => (await service(c)).propose(i), { write: true }),
  'review.proposals': op('Inspect agent proposals and whether their supporting inputs changed. Proposals are not reviews.', { ...target, ...page }, async (i, c) => { const p = (await service(c)).snapshot(i.pilotId); return paginate((p.proposals || []).map(proposal => { const criterion = p.criteria.find(c => c.id === proposal.criterionId); const current = proposal.kind === 'criterion' ? criterion && criterionFingerprint(p, criterion) : pilotFingerprint(p); return { ...proposal, freshness: current === proposal.fingerprint ? 'current' : 'changed' }; }), i); }),
  'review.record': op('Record a deliberate locally asserted human criterion review. Not authenticated sign-off. Agent sessions cannot use this operation.', { ...change, criterionId: id, status: z.enum(['met', 'unmet', 'blocked']), reviewer: z.string().trim().min(1).max(200), rationale: z.string().trim().min(1).max(4000), date: z.string(), confirmHumanReview: z.literal(true) }, async (i, c) => { if (c.transport === 'mcp') throw fault('HUMAN_REVIEW_REQUIRED', 'Use the human review UI; MCP can propose but cannot record human reviews.', 403); const { pilotId, confirmHumanReview, ...value } = i; return { project: await (await service(c)).review(pilotId, value), notice: 'Locally asserted human-entered review, not authenticated approval.' }; }, { write: true }),
  'decision.record': op('Record a deliberate locally asserted human proceed/hold/stop review. Agent sessions should propose instead.', { ...change, outcome: z.enum(['proceed', 'hold', 'stop']), reviewer: z.string().trim().min(1).max(200), rationale: z.string().trim().min(1).max(4000), date: z.string(), conditions: z.string().max(4000).default(''), visibility: z.enum(['internal', 'customer']).default('internal'), confirmHumanReview: z.literal(true) }, async (i, c) => { if (c.transport === 'mcp') throw fault('HUMAN_REVIEW_REQUIRED', 'Use the human review UI; MCP can only propose.', 403); const { pilotId, confirmHumanReview, ...value } = i; return { project: await (await service(c)).decide(pilotId, value) }; }, { write: true }),
  'pilot.export': op('Export customer HTML, evidence manifest, Fielddeck readout, or an explicitly acknowledged private backup.', { ...target, format: z.enum(['handover', 'manifest', 'fielddeck', 'backup']), includePrivate: z.boolean().default(false) }, async (i, c) => (await service(c)).export(i.pilotId, i.format, i.includePrivate)),
  'pilot.restore': op('Preview a validated private backup or explicitly replace only this pilot, preserving a recovery backup.', { ...change, backup: object, previewToken: z.string().uuid().optional(), dryRun: z.boolean().default(true), confirm: z.boolean().default(false) }, async (i, c) => { const checked = validateBackup(i.backup), s = await service(c), store = s.store(i.pilotId); store.expectRevision(i.revision); const previewToken = await restorePreview(c.root, i, i.revision); if (i.dryRun) return { valid: true, previewToken, criterionCount: checked.project.criteria.length, attachmentCount: checked.project.attachments.length, dryRun: true }; if (!i.confirm) throw fault('CONFIRMATION_REQUIRED', 'Preview and confirm replacement first.'); return s.library.withPilot(i.pilotId, async store => { const { writeJSON } = await import('./workspace.mjs'); const recovery = await store.backup(); await writeJSON(`${store.file}.before-restore-${fingerprint(recovery)}.json`, recovery); return { project: await store.replace(i.backup, i.revision) }; }, true); }, { write: true, destructive: true }),
};
export const product = makeProduct('proofpack', operations, async root => { await new ProofpackService(root).open(); });
